import React from 'react'
import Image from 'next/image'
import Footer from '../_components/Footer/Index'

function Index() {
    return (
        <>
            <div className='flex justify-center items-start pt-[100px] pb-[100px] max-lg:px-7'>

                <div className='max-w-[1000px] grid grid-cols-1 gap-2' >
                    <h2 className='text-xl font-bold'> Kullanıcı Sözleşmesi </h2>
                    <h2 className='text-lg font-bold'>Taraflar</h2>
                    <div className='grid grid-cols-1 gap-4'>
                        <p>İşbu üyelik sözleşmesi, www.akdagcisigorta.com (Kısaca "site" olarak anılacaktır)ile www.akdagcisigorta.com sitesine üye olurken "Üye"nin elektronik olarak onay vermesi ile karşılıklı olarak kabul edilerek yürürlüğe girmiştir.</p>
                        <p>Kullanıcı, Site'ye üye olurken verdiği elektronik onayla, Üyelik Sözleşmesi'nin tamamını okuduğunu, içeriğini bütünü ile anladığını ve tüm hükümlerini onayladığını kabul, beyan ve taahhüt eder.</p>
                        <h2 className='text-lg font-bold'>Tanımlar</h2>
                        <p>www.akdagcisigorta.com internet sitesinin faaliyetlerini yürüten Ayhan Akdağcı Sigorta şirketi, Muammer Sencer Cd. No:60E, 54300 Hendek/Sakarya adresinde mukim (Bundan böyle “satıcı” olarak anılacaktır)</p>
                        <p>Site: www.akdagcisigorta.com tarafından belirlenen çerçeve içerisinde çeşitli hizmetlerin ve içeriklerin sunulduğu çevrimiçi (on-line) ortamdan erişimi mümkün olan web sitesidir.</p>
                        <p>Üye: Site'ye üye olan ve Site'de sunulan Hizmet'lerden, işbu sözleşmede belirtilen koşullar dahilinde yararlanan gerçek veya tüzel kişi.</p>
                        <p>Alıcı: Site'de sunulan Hizmet'leri kullanmak suretiyle, satışa arz edilen mal ve/veya hizmetleri satın alan Üye.</p>
                        <p>Kullanıcı: www.akdagcisigorta.com web sitesini alışveriş yaparak ya da alışveriş yapmaksızın ziyaret eden kişidir.</p>
                        <p>Onaylama İşlemi: Üye tarafından, üyelik formunda www.akdagcisigorta.com sitesinden mesaj göndermesi ile Kullanıcı' nın üyeliğini aktif hale getirilebilmesi için yapılması gereken işlemdir.</p>
                        <p>Web Sitesi Kullanım Koşulları Ve Üyelik Sözleşmesi: Site vasıtasıyla sunulmakta olan ticari ve kişiye özel nitelikteki hizmetlerden yararlanacak gerçek ve/veya tüzel kişilerle www.akdagcisigorta.com internet sitesi arasında elektronik ortamda akdedilen işbu sözleşmedir.</p>
                        <h2 className='text-lg font-bold'>Sözleşmenin Konusu ve Kapsamı</h2>
                        <p>Üyelik Sözleşmesi'nin konusu, Site'de sunulan Hizmet'lerin, bu Hizmet'lerden yararlanma şartlarının ve tarafların hak ve yükümlülüklerinin tespitidir.</p>
                        <p>Üye Sözleşmesi'nin kapsamı, işbu sözleşme ve ekleri ile Site içerisinde yer alan, kullanıma, üyeliğe ve Hizmet'lere ilişkin olarak satıcı tarafından yapılmış olan bilcümle uyarı, yazı ve açıklama gibi beyanlardır. Üye, Üyelik Sözleşmesi'nin hükümlerini kabul etmekle, Site içinde yer alan, kullanıma, üyeliğe ve Hizmet'lere ilişkin olarak satıcı tarafından açıklanan her türlü beyanı da kabul etmiş olmaktadır. Üye, bahsi geçen beyanlarda belirtilen her türlü hususa uygun olarak davranacağını kabul, beyan ve taahhüt eder.</p>
                        <p>www.akdagcisigorta.com internet sitesi, Site üzerinden sunacağı hizmetler genel itibariyle Tüketici Hukuku mevzuatında tanımlanan elektronik ticaretten ibarettir.</p>
                        <p>www.akdagcisigorta.com internet sitesi, Site üzerinden vereceği hizmetler sınırlı sayıda olmamak üzere; www.akdagcisigorta.com adresinde satışa sunulan ürünlerin; Üye tarafından bedeli ödendikten sonra, tedarikçinin stok durumunun müsait olması halinde yani sözleşmenin satıcıya yüklediği; malın teslim edilmesi borcunun ifa edilebilir olması durumunda; taahhüt edilen sürede malın müşteriye kargo firması tarafından  www.akdagcisigorta.com adına ayıpsız olarak teslimidir.</p>
                        <p>www.akdagcisigorta.com Site üzerinden sunacağı hizmetlerin kapsamını ve niteliğini belirlemekte tamamen serbest olup, hizmetlere ilişkin olarak yapacağı değişiklikleri Site'de yayınlamasıyla yürürlüğe koymuş addedilir.</p>
                        <p>Site bünyesinde sunulacak hizmetlerden yararlanabilmek için kullanıcıların www.akdagcisigorta.com tarafından belirlenecek ve Site'nin ilgili bölümünün içeriğinde belirtilecek özellikleri taşıması gereklidir. www.akdagcisigorta.com bu özellikleri belirlemekte tamamen serbest olup, özelliklere ilişkin olarak yapacağı değişiklikleri Site'de yayınlamasıyla yürürlüğe koymuş addedilir.</p>
                        <h2 className='text-lg font-bold'>Üyelik ve Hizmet Kullanımı Şartları</h2>
                        <p>Üyelik, Site'nin ilgili bölümünden, Üye olmak isteyen kişi tarafından Site'ye üye olmak için gerekli kimlik bilgilerinin gönderilmesi suretiyle kayıt işleminin yaptırılması ve satıcı tarafından kayıt işleminin onaylanması ile tamamlanır. Üyelik işlemi tamamlanmadan, işbu sözleşmede tanımlanan Üye olma hak ve yetkisine sahip olunamaz.</p>
                        <p>Siteye üye olabilmek için reşit olmak, tüzel kişi üyeler için tüzel kişiyi temsil ve ilzam etmeye yetkili olmak ve satıcı tarafından işbu sözleşme kapsamında geçici olarak üyelikten uzaklaştırılmamış veya üyelikten süresiz yasaklanmış olmamak gerekmektedir. Reşit olmayan veya tüzel kişi üyeler için tüzel kişiyi temsil ve ilzam etmeye yetkili olmayan kişiler kanalıyla yapılan başvurular veya yukarıda belirtildiği gibi satıcı tarafından işbu sözleşme kapsamında geçici olarak üyelikten uzaklaştırılmış veya üyeliği askıya alınmış; üyelikten süresiz yasaklanmış olan kişiler tarafından yapılan başvurular Site kayıt işlemlerini tamamlamış olsa dahi Üyeliğin doğurduğu hakların kullanılmasına engeldir.</p>
                        <p>Satıcı her zaman herhangi bir gerekçe göstermeden, herhangi bir bildirimde bulunmadan ve herhangi bir tazminat ödeme yükümlülüğü bulunmadan ve derhal yürürlüğe girecek şekilde işbu sözleşmeyi tek taraflı olarak feshedebilir ve Üye’nin üyeliğine son verebilir veya sözleşmeyi feshetmeden Üye’nin üyeliğini geçici olarak durdurabilir. İşbu madde içerisinde belirtilen fesih, üyeliğe son verme ve üyeliği durdurma kararları tamamen işbu sözleşmeye aykırılık, sitede belirtilen kurallara aykırılık, Üye’nin işlemlerinin veya işlemleri sonucunda ortaya çıkan durumun satıcı bilgi güvenliği sistemi uyarınca bir risk oluşturduğunun satıcı tarafından tespit edilmesi veya satıcının ticari kararları veya satıcı tarafından ortaya çıkan durumun hukuki bir risk oluşturduğunun değerlendirilmesi doğrultusunda satıcının kendi iradesi ile verilecektir.</p>
                        <h2 className='text-lg font-bold'>Hak ve Yükümlülükler</h2>
                        <h2 className='text-lg font-bold'>Üye Hak ve Yükümlülükleri</h2>
                        <p>Üye, üyelik prosedürlerini yerine getirirken, Site'nin Hizmet'lerinden faydalanırken ve Site'deki Hizmet'lerle ilgili herhangi bir işlemi yerine getirirken, Üyelik Sözleşmesi'nde yer alan tüm şartlara, Site'nin ilgili yerlerinde belirtilen kurallara ve yürürlükteki tüm mevzuata uygun hareket edeceğini, işbu sözleşmede belirtilen tüm şart ve kuralları anladığını ve onayladığını kabul, beyan ve taahhüt eder.</p>
                        <p>Üye’lerin satıcı tarafından sunulan Hizmet'lerden yararlanabilmek amacıyla kullandıkları sisteme erişim araçlarının (Kullanıcı ismi, şifre v.b.) güvenliği, saklanması, üçüncü kişilerin bilgisinden uzak tutulması ve kullanılması durumlarıyla ilgili hususlar tamamen Üye’lerin  sorumluluğundadır. Üye’lerin, sisteme giriş araçlarının güvenliği, saklanması, üçüncü kişilerin bilgisinden uzak tutulması, kullanılması gibi hususlardaki tüm ihmal ve kusurlarından dolayı Üye’lerin ve/veya üçüncü kişilerin uğradığı veya uğrayabileceği zararlara istinaden satıcının, doğrudan veya dolaylı, herhangi bir sorumluluğu yoktur.</p>
                        <p>Üye’ler, Site dahilinde kendileri tarafından sağlanan bilgi ve içeriklerin doğru ve hukuka uygun olduğunu kabul, beyan ve taahhüt ederler. Satıcı, Üye’ler tarafından satıcıya iletilen veya Site üzerinden kendileri tarafından yüklenen, değiştirilen veya sağlanan bilgi ve içeriklerin doğruluğunu araştırma, bu bilgi ve içeriklerin güvenli, doğru ve hukuka uygun olduğunu taahhüt ve garanti etmekle yükümlü ve sorumlu olmadığı gibi, söz konusu bilgi ve içeriklerin yanlış veya hatalı olmasından dolayı ortaya çıkacak hiçbir zarardan da sorumlu tutulamaz.</p>
                        <p>Üye’ler, satıcının yazılı onayı olmadan, Üyelik Sözleşmesi kapsamındaki hak ve yükümlülüklerini, kısmen veya tamamen, herhangi bir üçüncü kişiye devredemezler.</p>
                        <p>Satıcının sunduğu Hizmet'lerden yararlananlar ve Site'yi kullananlar, yalnızca hukuka uygun amaçlarla Site üzerinde işlem yapabilirler. Üye’lerin, Site dahilinde yaptığı her işlem ve eylemdeki hukuki ve cezai sorumluluk kendilerine aittir. Her Üye, satıcı ve/veya başka bir üçüncü şahsın aynı veya şahsi haklarına veya malvarlığına tecavüz teşkil edecek şekilde, Site dahilinde bulunan resimleri, metinleri, görsel ve işitsel imgeleri, video kliplerini, dosyaları, veritabanlarını, katalogları ve listeleri çoğaltmayacağını, kopyalamayacağını, dağıtmayacağını, işlemeyeceğini, gerek bu eylemleri ile gerekse de başka yollarla satıcı ile doğrudan ve/veya dolaylı olarak rekabete girmeyeceğini kabul, beyan ve taahhüt eder. Satıcı Üye’lerin Üyelik Sözleşmesi hükümlerine ve/veya hukuka aykırı olarak Site üzerinde gerçekleştirdikleri faaliyetler nedeniyle üçüncü kişilerin uğradıkları veya uğrayabilecekleri zararlardan doğrudan ve/veya dolaylı olarak, hiçbir şekilde sorumlu tutulamaz.</p>
                        <p>Üye’ler de dahil olmak üzere üçüncü kişiler tarafından Site'de sağlanan hizmetlerden ve yayınlanan içeriklerden dolayı satıcının, satıcı çalışanlarının veya yöneticilerinin sorumluluğu bulunmamaktadır. Herhangi bir üçüncü kişi tarafından sağlanan ve yayınlanan bilgilerin, içeriklerin, görsel ve işitsel imgelerin doğruluğu ve hukuka uygunluğunun taahhüdü, bütünüyle bu eylemleri gerçekleştiren kişilerin sorumluluğundadır. Satıcı, Üye’ler de dahil olmak üzere üçüncü kişiler tarafından sağlanan hizmetlerin ve içeriklerin güvenliğini, doğruluğunu ve hukuka uygunluğunu taahhüt ve garanti etmemektedir.</p>
                        <p>Üye, satıcının Site üzerinden gerçekleştireceği her türlü kampanya ve çekiliş kapsamında, kampanyalara ve çekilişlere katılmaya hak kazanan Üye’lerin, üyelik bilgilerini kampanya ve çekiliş ile ilgili kişi ve kurumlarla paylaşacağını ve bu sebeple satıcıdan herhangi bir tazminat talebinde bulunmayacağını kabul, beyan ve taahhüt eder.</p>
                        <p>Üye, Portal üzerinde gerçekleştirdiği işlemler ilgili olarak, reklam veren, üretici, vergi mükellefi veya benzeri sıfatlarla ilgili mevzuatın gerektirdiği önlem ve prosedürleri yerine getirmek zorunda olduğunu, bu önlem ve prosedürlerle ilgili satıcının herhangi bir yetki ve sorumluluğu bulunmadığını, işbu madde içerisinde belirtilen kapsamda önlem ve prosedürlerin yerine getirilmemesi sonucunu doğuracak tüm ihmal ve kusurlarından dolayı diğer Üyelerin, satıcının ve/veya üçüncü kişilerin uğradığı veya uğrayabileceği zararlardan sorumlu olacağını kabul, beyan ve taahhüt eder.
                            Üye, kayıt için gerekli olan bölümleri doldurup elektronik posta adresini onayladıktan sonra işbu sözleşmede belirtilen şartlara uymak koşuluyla, elektronik posta adresini ve şifresini girerek Siteyi kullanmaya başlayabilir.
                        </p>
                        <p>Üye, Site ve hizmetlerinden yararlanırken, Türk Ceza Kanunu, Türk Ticaret Kanunu, Fikir ve Sanat Eserleri Kanunu, Marka ve Patent Haklarının Korunması ile ilgili Kanun Hükmünde Kararnameler ve yasal düzenlemeler, Borçlar Yasası, diğer ilgili mevzuat hükümleri ile Sitenin hizmetlerine ilişkin olarak yayımlayacağı her türlü duyuru ve bildirimlere uymayı kabul eder. Bu bildirimlere ve yasalara aykırı kullanım sebebiyle doğabilecek hukuki, cezai ve mali her türlü sorumluluk üyeye aittir.</p>
                        <p>Siteyi ziyaret eden üyelerin bilgileri (ziyaret sıklığı, ziyaret zamanları vb.) onlara daha iyi hizmet edebilmek amacı ile takip edilmektedir. Bu bilgiler, gizlilik şartlarına bağlı kalınarak, içeriği genişletmek ve iyileştirmek amacı ile reklam vb. konularda işbirliği yapılan firmalarla paylaşılmaktadır. Buradaki amaç, sitenin kullanıcılarına sunduğu hizmeti geliştirmek ve Sitenin sunduğu içeriği zenginleştirmektir.</p>
                        <h2 className='text-lg font-bold'>Alıcı'ların Hak ve Yükümlülükleri</h2>
                        <p>Alıcı, sergilenen ürüne almak üzere talepte bulunmak suretiyle, ürün açıklaması ile beraber satıcı tarafından belirlenmiş satış şartlarını ve usullerini de kabul etmiş sayılır.</p>
                        <p>Alıcı, Site'de Üretici’ler tarafından satışa arz edilen ürünlerin defolu olup olmaması, Yasaklı Ürünler' den olup olmaması, kaçak olup olmaması, niteliği, orjinalliği, ürünün tanıtımında kullanılan yazılı ve/veya görüntülü açıklamaların doğruluğu ve tamlığı da dahil ancak bunlarla sınırlı olmamak üzere, ürünün aslı ile ilgili hiçbir konu hakkında satıcının bilgi sahibi olmadığı ve olması gerekmediğini ve bunları taahhüt ve garanti etmek yükümlülüğü bulunmadığını kabul ve beyan eder.</p>
                        <p>Alıcı, Site üzerinde gerçekleşmekte olan alım-satım sürecinin herhangi bir aşamasında ve her ne sebeple olursa olsun, Üretici’nin ürünü satmaktan ve teslim etmekten vazgeçmesi halinde, bu durumdan ötürü satıcının hiçbir sorumluluğu ve yükümlülüğü olmayacağını; satıcıdan, satın almaya çalıştığı ürünün veya muadilinin, her ne suretle olursa olsun tedarikini veya buradan hareketle herhangi bir tazminat ödenmesini talep edemeyeceğini kabul, beyan ve taahhüt eder.</p>
                        <p>Alıcı 6205 sayılı Tüketicinin Korunması Hakkındaki Kanun ve Mesafeli Sözleşmeler Yönetmeliği gereğince satıcının ürünlere ilişkin ön bilgilendirme formu ve mesafeli satış sözleşmesini Güvenli alışveriş sistemi Hizmeti içerisinde oluşturacağını kabul, beyan ve taahhüt eder.</p>
                        <p>Alıcı, Site'de 6205 sayılı Tüketicinin Korunması Hakkındaki Kanun ve Mesafeli Sözleşmeler Yönetmeliği çerçevesinde satıcının kendisine ait üyelik bilgilerini ve Üretici’nin satışa konu ürüne ilişkin verdiği bilgileri esas alarak düzenlenen ön bilgilendirme formu ve mesafeli satış sözleşmesini onaylayacağını kabul, beyan ve taahhüt eder. </p>
                        <h2 className='text-lg font-bold'>Satıcının Hak ve Yükümlülükleri</h2>
                        <p>Satıcı Site'de sunulan Hizmet'leri ve içerikleri her zaman değiştirebilme; Üye'lerin sisteme yükledikleri bilgileri ve içerikleri, Üye’ler de dahil olmak üzere, üçüncü kişilerin erişimine kapatabilme ve silme hakkını saklı tutmaktadır. Satıcı, bu hakkını, hiçbir bildirimde bulunmadan ve önel vermeden kullanabilir. Üye’ler, satıcının talep ettiği değişiklik ve/veya düzeltmeleri ivedi olarak yerine getirmek zorundadırlar. Satıcı tarafından talep edilen değişiklik ve/veya düzeltme istekleri, gerekli görüldüğü takdirde, satıcı tarafından yapılabilir. Satıcı tarafından talep edilen değişiklik ve/veya düzeltme taleplerinin Üye’ler tarafından zamanında yerine getirilmemesi sebebiyle doğan veya doğabilecek zararlar, hukuki ve cezai sorumluluklar tamamen Üye’lera aittir.</p>
                        <p>Satıcı Site'de yer alan üyelik bilgilerini, Kullanıcı güvenliği, kendi yükümlülüğünü ifa ve Site'nin ana sayfasında adı geçen grup şirketleri tarafından oluşturulan internet siteleri ve kendi bünyesindeki Site (www.akdagcisigorta.com) ile ilgili pazarlama, tanıtım ve iletişim yapmak ve bazı istatistiki değerlendirmeler için dilediği biçimde kullanabilir. Bunları bir veritabanı üzerinde tasnif edip muhafaza edebilir.</p>
                        <p>Satıcı, Site'de sağlanan Hizmet'ler kapsamında Üye’ler arasında ortaya çıkan uyuşmazlıklarda, arabulucu veya hakem sıfatlarıyla görev almaz.</p>
                        <p>Satıcı, Kullanıcılar arasında site üzerinden gerçekleşen ve Site'nin işleyişine ve/veya Üyelik Sözleşmesine ve/veya Site'nin genel kurallarına ve/veya genel ahlak kurallarına aykırı ve “Satıcı” veya “X” tarafından kabul edilmesi mümkün olmayan mesajların ve/veya içeriklerin tespit edilmesi amacıyla gerekli içerik ve/veya mesaj taraması yapabilir ve tespit ettiği mesaj ve/veya içerikleri istediği zaman ve şekilde erişimden kaldırabilir; Satıcı, bu mesaj ve/veya içeriği oluşturan Üye’yi yazılı uyarabilir ve/veya Üye’nin üyeliğine, herhangi bir ihbar yapmadan, geçici veya kalıcı olarak, son verebilir.</p>
                        <p>Üye’ler ve satıcı hukuken bağımsız taraflardır. Aralarında ortaklık, temsilcilik veya işçi-işveren ilişkisi yoktur. Üyelik Sözleşmesi'nin onaylanması ve uygulanması sonucunda, ortaklık, temsilcilik veya işçi-işveren ilişkisi doğmaz.</p>
                        <p>Üye’lerın, Site'ye üye olurken sisteme yükledikleri "kullanıcı isimleri"  işbu Üyelik Sözleşmesi içinde yer alan hükümlere tabi olup, Üye’lerin "kullanıcı ismi" belirlerken üçüncü şahısların telif hakkı, marka, ticari unvan gibi yasal haklarını ihlal etmemesi gerekmektedir. Üye’lerın işbu madde hükmüne aykırı davranması durumunda, satıcı Üyelik Sözleşmesi'ne aykırı bu durumun düzeltilmesini Üye’den talep edebileceği gibi dilerse Üye’ye önceden haber vermeksizin Üye’nin üyeliğini geçici veya kalıcı olarak iptal edebilir.</p>
                        <p>Satıcı, Site üzerinden yapılan satışlara ilişkin ön bilgilendirme formu ve mesafeli satış sözleşmelerini 3 yıl süre ile saklayacağını ve bu süre içerisinde işbu mesafeli satış sözleşmesini ve ön bilgilendirme formunu Alıcı ve Üretici’nin talebi ile paylaşacağını kabul, beyan ve taahhüt eder. satıcı müşterilerine ait kredi kartı bilgilerini sistemde kayıtlı olarak tutmamaktadır.</p>
                        <p>Satıcı tarafından www.akdagcisigorta.cominternet sitesinin iyileştirilmesi, geliştirilmesine yönelik olarak ve/veya yasal mevzuat çerçevesinde siteye erişmek için kullanılan İnternet servis sağlayıcısının adı ve Internet Protokol (IP) adresi, siteye erişilen tarih ve saat, sitede bulunulan sırada erişilen sayfalar ve siteye doğrudan bağlanılmasını sağlayan Web sitesinin Internet adresi gibi birtakım bilgiler toplanabilir.</p>
                        <p>Satıcı üyelerine daha iyi hizmet sunmak, ürünlerini ve hizmetlerini iyileştirmek, sitenin kullanımını kolaylaştırmak için kullanımını Üye’lerinin özel tercihlerine ve ilgi alanlarına yönelik çalışmalarda üyelerin kişisel bilgilerini kullanabilir. Satıcı, üyenin www.akdagcisigorta.cominternet sitesi üzerinde yaptığı hareketlerin kaydını bulundurma hakkını saklı tutar.</p>
                        <p>Satıcı, üye, kullanıcı veya alıcının www.akdagcisigorta.com internet sitesi kurallarını yada iş bu sözleşmede öngörülen herhangi bir yükümlülüğü veya herhangi kanun, yönetmelik ve sair mevzuata aykırı herhangi bir eylem ve işlem nedeniyle herhangi bir ihbar ve ihtarda bulunmaksızın derhal kullanım hakkını sınırlandırabilir, durdurabilir veya üyeliği iptal edebilir. Bu hallerde üye, kullanıcı veya alıcı, satıcıdan herhangi bir menfi veya müspet zarar ve ziyan, hak ve alacak talep ve tahsil edemez.</p>
                        <h2 className='text-lg font-bold'>Fikri Mülkiyet Hakları</h2>
                        <p>Site'nin (tasarım, metin, imge, html kodu ve diğer kodlar da dahil ve fakat bunlarla sınırlı olmamak kaydıyla) tüm elemanları (Satıcı telif haklarına tabi çalışmalar) satıcıya ait olarak ve/veya satıcı tarafından üçüncü bir kişiden alınan lisans hakkı altında kullanılmaktadır. Üye’ler, satıcı Hizmet'lerini, satıcıbilgilerini ve satıcının telif haklarına tabi çalışmalarını yeniden satamaz, paylaşamaz, dağıtamaz, sergileyemez, çoğaltamaz, bunlardan türemiş çalışmalar yapamaz veya hazırlayamaz, veya başkasının satıcının Hizmet'lerine erişmesine veya kullanmasına izin veremez; aksi takdirde, lisans verenler de dahil ancak bunlarla sınırlı olmaksızın, üçüncü kişilerin uğradıkları zararlardan dolayı satıcıdan talep edilen tazminat miktarını ve mahkeme masrafları ve avukatlık ücreti de dahil ancak bununla sınırlı olmamak üzere diğer her türlü yükümlülükleri karşılamakla sorumlu olacaklardır.</p>
                        <p>Satıcının satıcı Hizmet'leri, satıcı bilgileri, satıcı telif haklarına tabi çalışmalar, satıcı ticari markaları, satıcı ticari görünümü veya Site vasıtasıyla sahip olduğu her tür maddi ve fikri mülkiyet hakları da dahil tüm malvarlığı, aynı ve şahsi hakları, ticari bilgi ve know-how'a yönelik tüm hakları saklıdır.</p>
                        <h2 className='text-lg font-bold'>Sözleşme Değişiklikleri</h2>
                        <p>İşbu sözleşme üyenin üyeliğini iptal etmesi veya satıcı tarafından üyeliğinin iptal edilmesine kadar yürürlükte kalacaktır. Satıcı üyenin üyelik sözleşmesinin herhangi bir hükmünü ihlal etmesi durumunda üyenin üyeliğini iptal ederek sözleşmeyi tek taraflı olarak feshedebilecektir.</p>
                        <h2 className='text-lg font-bold'>Sorumluluğun Sınırlandırılması</h2>
                        <p>www.akdagcisigorta.com, Site'ye erişilmesi, Site'nin ya da Site'deki bilgilerin ve diğer verilerin programların vs. kullanılması sebebiyle, sözleşmenin ihlali, haksız fiil, ya da başkaca sebeplere binaen, doğabilecek doğrudan ya da dolaylı hiçbir zarardan sorumlu değildir. www.akdagcisigorta.com sözleşmenin ihlali, haksız fiil, ihmal veya diğer sebepler neticesinde; işlemin kesintiye uğraması, hata, ihmal, kesinti hususunda herhangi bir sorumluluk kabul etmez. Bu Site’ye ya da link verilen diğer web sitelerine erişilmesi ya da Site'nin kullanılması ile www.akdagcisigorta.com işletmesinin, kullanım/ziyaret sonucunda, doğabilecek her tür sorumluluktan, mahkeme ve diğer masraflar da dahil olmak üzere her tür zarar ve talep hakkından ayrı kılındığı kabul edilmektedir.</p>
                        <h2 className='text-lg font-bold'>Devir</h2>
                        <p>www.akdagcisigorta.com bu sözleşmeyi bildirimsiz olarak istediği zaman kısmen veya bütünüyle devredebilir. Ancak Kullanıcı ve Üye bu sözleşmeyi veya herhangi bir kısmını başka bir tarafa devredemez. Bu türden bir devir girişimi geçersizdir.</p>
                        <h2 className='text-lg font-bold'>Mücbir Sebepler</h2>
                        <p>Hukuken mücbir sebep sayılan tüm durumlarda,  işbu Kullanım Koşulları ve Üyelik Sözleşmesini geç ifa etmekten veya ifa etmemekten dolayı yükümlü değildir. Bu ve bunun gibi durumlar, www.akdagcisigorta.com açısından, gecikme veya ifa etmeme veya temerrüt addedilmeyecek veya bu durumlar için www.akdagcisigorta.com işletmesinin herhangi bir tazminat yükümlülüğü doğmayacaktır.</p>
                        <h2 className='text-lg font-bold'>Uygulanacak Hukuk ve Yetki</h2>
                        <p>İşbu sözleşmenin uygulanmasında, Sanayi ve Ticaret Bakanlığınca ilan edilen değere kadar Tüketici Hakem Heyetleri ile satıcının yerleşim yerindeki TÜKETICI MAHKEMELERI yetkilidir. Siparişin elektronik ortamda onaylanması durumunda, Alıcı is bu sözleşmenin tüm hükümlerini kabul etmiş sayılır. Taraflar arasında ve/veya 3.şahısların şikayetleri ile ilgili herhangi bir uyuşmazlık olduğunda satıcının kayıt ve belgeleri, mail yazışmaları, internet sitesi üzerinde yer alan sistem kayıtları(bilgisayar-ses kayıtları gibi manyetik ortamdaki kayıtlar dahil) münhasıran HMK 193. madde anlamında kesin delil teşkil edecektir.</p>
                        <h2 className='text-lg font-bold'>Yürürlük</h2>
                        <p>Üyenin, üyelik kaydı yapması üyenin üyelik sözleşmesinde yer alan tüm maddeleri okuduğu ve üyelik sözleşmesinde yer alan maddeleri kabul ettiği anlamına gelir. İşbu Sözleşme üyenin üye olması anında akdedilmiş ve karşılıklı olarak yürürlülüğe girmiştir. Satıcı dilediği zaman işbu sözleşme hükümlerinde değişikliğe gidebilir, değişiklikler, sürüm numarası ve değişiklik tarihi belirtilerek site üzerinden yayınlanır ve aynı tarihte yürürlüğe girer.</p>



                        <p>OKUDUM-KABUL ETTİM ve ONAYLADIM <br />
                            Üye

                        </p>





                    </div>

                </div>



            </div>

            <Footer />

        </>
    )
}

export default Index